# # frontend/Dockerfile-dev

# # This is the build file for the frontend module, Docker will use this to setup the frontend container image.

# # Installs the node image
# FROM node

# # Creates the frontend directory in the container
# RUN mkdir -p /srv/app/frontend
# # Sets the working directory to the frontend directory
# WORKDIR /srv/app/frontend


# # Copies the package.json to the container
# COPY package*.json /srv/app/frontend/

# # Installs the frontend dependencies
# RUN npm install

# # Copies the files from the frontend directory to the container
# COPY . /srv/app/frontend/

# # Runs the frontend
# CMD ["npm", "start"]