version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    networks:
            testing_net:
                    ipv4_address: 172.28.1.2
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    networks:
            testing_net:
                    ipv4_address: 172.28.1.3
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
            testing_net:
                    ipv4_address: 172.28.1.4

networks:
        testing_net:
                ipam:
                        driver: default
                        config:
                                - subnet: 172.28.0.0/16
