pipeline {
    agent any {
        stages {
            stage('Build') {
                steps {
                    echo 'Starting Build'
                    checkout scm
                    sh 'npm install -y'
                    sh 'docker-compose build'
                    sh 'docker-compose up'
                    echo 'BUILT THE CONTAINERS!!'
                


                }
                stage('Test') {
                    steps {
                        sh 'cd UnitTesting'
                        sh 'npm install -y'
                        sh 'jasmine'

                    }
                }
                stage('Deploy')
                steps {

                }


            }
        }
    }
}